language: cpp

jobs:
 include:
  - os: linux
    name: Qt 4.8
    dist: trusty
    addons:
      apt:
        sources:
          - sourceline: "ppa:beineri/opt-qt487-trusty"
        packages:
          - opt-qt4-qmake opt-qt4-dev-tools opt-libqt4-dev opt-libqt4-dev-bin opt-libqt4-opengl-dev
    compiler: gcc
    script:
     - source /opt/qt*/bin/qt*-env.sh
     - qmake PREFIX=/usr -v
     - qmake PREFIX=/usr
     - make -j$(nproc)
    
  - os: linux
    name: Linux amd64
    dist: trusty
    addons:
      apt:
        sources:
          - sourceline: "ppa:beineri/opt-qt-5.10.1-trusty"
        packages:
          - qt510base
    compiler: gcc
    script:
     - source /opt/qt*/bin/qt*-env.sh
     - qmake PREFIX=/usr -v
     - qmake PREFIX=/usr
     - make -j$(nproc)
    after_success:
     - make install INSTALL_ROOT=AppDir
     - wget https://github.com/leozide/leocad/releases/download/v19.07.1/Library-Linux-14384.zip -O library.zip
     - unzip library.zip
     - mkdir -p AppDir/usr/share/leocad
     - mv library.bin AppDir/usr/share/leocad/library.bin
     - wget -c "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
     - chmod a+x linuxdeployqt*.AppImage 
     - unset QTDIR; unset QT_PLUGIN_PATH ; unset LD_LIBRARY_PATH
     - export VERSION=$(git rev-parse --short HEAD)
     - ./linuxdeployqt*.AppImage ./AppDir/usr/share/applications/*.desktop -bundle-non-qt-libs
     - ./linuxdeployqt*.AppImage --appimage-extract
     - export PATH=$(readlink -f ./squashfs-root/usr/bin/):$PATH
     - ./squashfs-root/usr/bin/appimagetool AppDir/
     - mv ./LeoCAD-$VERSION-x86_64.AppImage ./LeoCAD-Linux-$VERSION-x86_64.AppImage 
     - 'curl -s -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/repos/leozide/leocad/commits/master -o repo.txt'
     - 'export REMOTE=$(grep -Po ''(?<=: \")(([a-z0-9])\w+)(?=\")'' -m 1 repo.txt)'
     - export LOCAL=$(git rev-parse HEAD)
     - if [[ "$REMOTE" != "$LOCAL" ]]; then echo "Build no longer current. $REMOTE vs $LOCAL - aborting upload."; exit 0; fi;
     - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
     - bash upload.sh LeoCAD*.AppImage*
     
  - os: linux
    name: Linux arm64
    arch: arm64
    dist: trusty
    addons:
      apt:
        packages:
          - qt5-default
          - qtbase5-dev
          - qttools5-dev-tools
          - libqt5opengl5-dev
          - zip
    compiler: gcc
    script:
     - qmake -v
     - qmake PREFIX=/usr
     - make -j$(nproc)
     - cp build/release/leocad .
     - export VERSION=$(git rev-parse --short HEAD)
     - zip LeoCAD-Linux-$VERSION-arm64.zip leocad
     - 'curl -s -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/repos/leozide/leocad/commits/master -o repo.txt'
     - 'export REMOTE=$(grep -Po ''(?<=: \")(([a-z0-9])\w+)(?=\")'' -m 1 repo.txt)'
     - export LOCAL=$(git rev-parse HEAD)
     - if [[ "$REMOTE" != "$LOCAL" ]]; then echo "Build no longer current. $REMOTE vs $LOCAL - aborting upload."; exit 0; fi;
     - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
     - bash upload.sh LeoCAD*.zip

  - os: osx
    name: macOS
    osx_image: xcode11
    compiler: clang
    addons:
      homebrew:
        packages:
          - grep
          - qt5
    install:
     - brew link --force qt5
     - wget https://github.com/leozide/povray/releases/download/continuous/povray
     - wget https://github.com/leozide/leocad/releases/download/v19.07.1/Library-Linux-14384.zip -O library.zip
     - unzip library.zip
    script:
     - qmake -v
     - qmake
     - make -j$(sysctl -n hw.ncpu)
     - cd build/release
     - macdeployqt LeoCAD.app -dmg
     - mv LeoCAD.dmg LeoCAD-macOS-$(git rev-parse --short HEAD).dmg
    after_success:
     - 'curl -s -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/repos/leozide/leocad/commits/master -o repo.txt'
     - 'export REMOTE=$(ggrep -Po ''(?<=: \")(([a-z0-9])\w+)(?=\")'' -m 1 repo.txt)'
     - export LOCAL=$(git rev-parse HEAD)
     - if [[ "$REMOTE" != "$LOCAL" ]]; then echo "Build no longer current. $REMOTE vs $LOCAL - aborting upload."; exit 0; fi;
     - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
     - bash upload.sh LeoCAD*.dmg*

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/
